version: "3"

services:

  mongo:
    image: mongo:4.2-bionic
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 127.0.0.1:27017:27017

  mailhog:
    image: mailhog/mailhog
    ports:
      - 127.0.0.1:8025:8025
      - 127.0.0.1:1025:1025

  caddy:
    image: caddy
#    command: [ 'caddy', 'run', '--config', '/etc/caddy/config.json', '--resume' ]
    command: [ 'caddy', 'run', '--config', '/etc/caddy/config.json' ]
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:2019:2019
    volumes:
      - ./data/sites:/sites
      - ./caddy/config.json:/etc/caddy/config.json:ro
#      - ./data/caddy/data:/data
#      - ./data/caddy/config:/config
      - ./data/ca-cert.pem:/ca-cert.pem:ro
